// Mocks generated by Mockito 5.4.5 from annotations
// in web3_smartwatch_sdk/test/web3_smartwatch_sdk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openapi/openapi.dart' as _i9;
import 'package:openapi/src/api/health_api.dart' as _i4;
import 'package:openapi/src/api/user_api.dart' as _i5;
import 'package:openapi/src/model/api_search_address_address_get200_response.dart'
    as _i10;
import 'package:openapi/src/model/api_search_did_did_get200_response.dart'
    as _i11;
import 'package:openapi/src/model/api_user_address_balance_get200_response.dart'
    as _i12;
import 'package:openapi/src/model/api_user_address_get200_response.dart'
    as _i13;
import 'package:openapi/src/model/api_user_address_nfts_get200_response.dart'
    as _i14;
import 'package:web3_smartwatch_sdk/src/interface.dart' as _i6;
import 'package:web3_smartwatch_sdk/src/web3_smartwatch_sdk.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthApi_2 extends _i1.SmartFake implements _i4.HealthApi {
  _FakeHealthApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserApi_3 extends _i1.SmartFake implements _i5.UserApi {
  _FakeUserApi_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBalance_5 extends _i1.SmartFake implements _i6.Balance {
  _FakeBalance_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateWalletResponse_6 extends _i1.SmartFake
    implements _i6.CreateWalletResponse {
  _FakeCreateWalletResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i7.FlutterSecureStorage {
  @override
  _i8.Future<void> write({
    required String? key,
    required String? value,
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> read({
    required String? key,
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<bool> containsKey({
    required String? key,
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> delete({
    required String? key,
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, String>> readAll({
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<void> deleteAll({
    _i7.IOSOptions? iOptions = _i7.IOSOptions.defaultOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [Openapi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenapi extends _i1.Mock implements _i9.Openapi {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
            returnValueForMissingStub: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.HealthApi getHealthApi() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthApi, []),
            returnValue: _FakeHealthApi_2(
              this,
              Invocation.method(#getHealthApi, []),
            ),
            returnValueForMissingStub: _FakeHealthApi_2(
              this,
              Invocation.method(#getHealthApi, []),
            ),
          )
          as _i4.HealthApi);

  @override
  _i5.UserApi getUserApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUserApi, []),
            returnValue: _FakeUserApi_3(
              this,
              Invocation.method(#getUserApi, []),
            ),
            returnValueForMissingStub: _FakeUserApi_3(
              this,
              Invocation.method(#getUserApi, []),
            ),
          )
          as _i5.UserApi);
}

/// A class which mocks [UserApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserApi extends _i1.Mock implements _i5.UserApi {
  @override
  _i8.Future<_i2.Response<_i10.ApiSearchAddressAddressGet200Response>>
  apiSearchAddressAddressGet({
    required String? address,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiSearchAddressAddressGet, [], {
              #address: address,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i8.Future<
              _i2.Response<_i10.ApiSearchAddressAddressGet200Response>
            >.value(
              _FakeResponse_4<_i10.ApiSearchAddressAddressGet200Response>(
                this,
                Invocation.method(#apiSearchAddressAddressGet, [], {
                  #address: address,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<
              _i2.Response<_i10.ApiSearchAddressAddressGet200Response>
            >.value(
              _FakeResponse_4<_i10.ApiSearchAddressAddressGet200Response>(
                this,
                Invocation.method(#apiSearchAddressAddressGet, [], {
                  #address: address,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i8.Future<
            _i2.Response<_i10.ApiSearchAddressAddressGet200Response>
          >);

  @override
  _i8.Future<_i2.Response<_i11.ApiSearchDidDidGet200Response>>
  apiSearchDidDidGet({
    required String? did,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiSearchDidDidGet, [], {
              #did: did,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i8.Future<
              _i2.Response<_i11.ApiSearchDidDidGet200Response>
            >.value(
              _FakeResponse_4<_i11.ApiSearchDidDidGet200Response>(
                this,
                Invocation.method(#apiSearchDidDidGet, [], {
                  #did: did,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<
              _i2.Response<_i11.ApiSearchDidDidGet200Response>
            >.value(
              _FakeResponse_4<_i11.ApiSearchDidDidGet200Response>(
                this,
                Invocation.method(#apiSearchDidDidGet, [], {
                  #did: did,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Response<_i11.ApiSearchDidDidGet200Response>>);

  @override
  _i8.Future<_i2.Response<_i12.ApiUserAddressBalanceGet200Response>>
  apiUserAddressBalanceGet({
    required String? address,
    bool? includeZeroBalance = false,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressBalanceGet, [], {
              #address: address,
              #includeZeroBalance: includeZeroBalance,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i8.Future<
              _i2.Response<_i12.ApiUserAddressBalanceGet200Response>
            >.value(
              _FakeResponse_4<_i12.ApiUserAddressBalanceGet200Response>(
                this,
                Invocation.method(#apiUserAddressBalanceGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<
              _i2.Response<_i12.ApiUserAddressBalanceGet200Response>
            >.value(
              _FakeResponse_4<_i12.ApiUserAddressBalanceGet200Response>(
                this,
                Invocation.method(#apiUserAddressBalanceGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i8.Future<
            _i2.Response<_i12.ApiUserAddressBalanceGet200Response>
          >);

  @override
  _i8.Future<_i2.Response<_i13.ApiUserAddressGet200Response>>
  apiUserAddressGet({
    required String? address,
    bool? includeZeroBalance = false,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressGet, [], {
              #address: address,
              #includeZeroBalance: includeZeroBalance,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i8.Future<
              _i2.Response<_i13.ApiUserAddressGet200Response>
            >.value(
              _FakeResponse_4<_i13.ApiUserAddressGet200Response>(
                this,
                Invocation.method(#apiUserAddressGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<
              _i2.Response<_i13.ApiUserAddressGet200Response>
            >.value(
              _FakeResponse_4<_i13.ApiUserAddressGet200Response>(
                this,
                Invocation.method(#apiUserAddressGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Response<_i13.ApiUserAddressGet200Response>>);

  @override
  _i8.Future<_i2.Response<_i14.ApiUserAddressNftsGet200Response>>
  apiUserAddressNftsGet({
    required String? address,
    bool? includeMetadata = true,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressNftsGet, [], {
              #address: address,
              #includeMetadata: includeMetadata,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i8.Future<
              _i2.Response<_i14.ApiUserAddressNftsGet200Response>
            >.value(
              _FakeResponse_4<_i14.ApiUserAddressNftsGet200Response>(
                this,
                Invocation.method(#apiUserAddressNftsGet, [], {
                  #address: address,
                  #includeMetadata: includeMetadata,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<
              _i2.Response<_i14.ApiUserAddressNftsGet200Response>
            >.value(
              _FakeResponse_4<_i14.ApiUserAddressNftsGet200Response>(
                this,
                Invocation.method(#apiUserAddressNftsGet, [], {
                  #address: address,
                  #includeMetadata: includeMetadata,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Response<_i14.ApiUserAddressNftsGet200Response>>);
}

/// A class which mocks [Web3SmartwatchSdk].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeb3SmartwatchSdk extends _i1.Mock implements _i15.Web3SmartwatchSdk {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
            returnValueForMissingStub: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setCurrentWalletAddress(String? address) => super.noSuchMethod(
    Invocation.method(#setCurrentWalletAddress, [address]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i6.Balance> getAddressBalance(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBalance, [address]),
            returnValue: _i8.Future<_i6.Balance>.value(
              _FakeBalance_5(
                this,
                Invocation.method(#getAddressBalance, [address]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Balance>.value(
              _FakeBalance_5(
                this,
                Invocation.method(#getAddressBalance, [address]),
              ),
            ),
          )
          as _i8.Future<_i6.Balance>);

  @override
  _i8.Future<_i6.Balance?> getAddressBalanceByToken(
    String? address,
    String? contractAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBalanceByToken, [
              address,
              contractAddress,
            ]),
            returnValue: _i8.Future<_i6.Balance?>.value(),
            returnValueForMissingStub: _i8.Future<_i6.Balance?>.value(),
          )
          as _i8.Future<_i6.Balance?>);

  @override
  _i8.Future<_i6.CreateWalletResponse> createWallet({String? did}) =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, [], {#did: did}),
            returnValue: _i8.Future<_i6.CreateWalletResponse>.value(
              _FakeCreateWalletResponse_6(
                this,
                Invocation.method(#createWallet, [], {#did: did}),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i6.CreateWalletResponse>.value(
                  _FakeCreateWalletResponse_6(
                    this,
                    Invocation.method(#createWallet, [], {#did: did}),
                  ),
                ),
          )
          as _i8.Future<_i6.CreateWalletResponse>);

  @override
  _i8.Future<_i6.Wallet?> getWallet() =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, []),
            returnValue: _i8.Future<_i6.Wallet?>.value(),
            returnValueForMissingStub: _i8.Future<_i6.Wallet?>.value(),
          )
          as _i8.Future<_i6.Wallet?>);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.HealthApi getHealthApi() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthApi, []),
            returnValue: _FakeHealthApi_2(
              this,
              Invocation.method(#getHealthApi, []),
            ),
            returnValueForMissingStub: _FakeHealthApi_2(
              this,
              Invocation.method(#getHealthApi, []),
            ),
          )
          as _i4.HealthApi);

  @override
  _i5.UserApi getUserApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUserApi, []),
            returnValue: _FakeUserApi_3(
              this,
              Invocation.method(#getUserApi, []),
            ),
            returnValueForMissingStub: _FakeUserApi_3(
              this,
              Invocation.method(#getUserApi, []),
            ),
          )
          as _i5.UserApi);
}
